name: Build Electron App

on:
  push:
    tags:
      - v*.*.*
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # This is nessisary because newer versions of pthon no longer have the 'distutils' package
      - name: Install python-setuptools
        if: startsWith(matrix.os, 'macos')
        run: brew install python-setuptools

      - name: Install Snapcraft
        if: startsWith(matrix.os, 'ubuntu')
        uses: samuelmeuli/action-snapcraft@v2

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # https://github.com/electron-userland/electron-builder/issues/6289#issuecomment-1042620422
      # https://pnpm.io/npmrc#node-linker
      - name: Create .npmrc
        run: |
          echo "node-linker=hoisted" >> .npmrc

      - name: Install Dependencies
        run: pnpm install

      - name: Build app
        run: pnpm build

      - name: Build Electron
        run: pnpm electron-builder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: |
            build/*.exe
            build/*.dmg
            build/*.AppImage
            build/*.snap
            build/*.tar.gz
            build/*.zip
